Repository Securrency-OSS/mirai, pull requests merged in 2023-09, with the labels that each got.

#192 feat: Add support for gradient in outline border.
  examples/mirai_gallery/assets/json/text_field_example.json
  examples/mirai_gallery/ios/Runner.xcodeproj/project.pbxproj
  examples/mirai_gallery/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  examples/mirai_gallery/pubspec.lock
  packages/mirai/lib/src/framework/ui/mirai_outline_input_border.dart
  packages/mirai/lib/src/parsers/mirai_input_border/mirai_input_border.dart
  packages/mirai/lib/src/parsers/mirai_input_border/mirai_input_border.freezed.dart
  packages/mirai/lib/src/parsers/mirai_input_border/mirai_input_border.g.dart
Labels: enhancement, feature

#194 feat: Mirai modal bottom sheet action
  examples/mirai_gallery/assets/json/bottom_sheet_example.json
  examples/mirai_gallery/assets/json/home_screen.json
  examples/mirai_gallery/pubspec.lock
  packages/mirai/lib/src/action_parsers/action_parsers.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action.g.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_none_action/mirai_none_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_request_action/mirai_request_action_parser.dart
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/framework/mirai_action_parser.dart
  packages/mirai/lib/src/framework/mirai_registry.dart
  packages/mirai/lib/src/navigation/mirai_navigator.dart
  packages/mirai/lib/src/utils/action_type.dart
Labels: feature, breaking-change

#195 feat: Mirai show dialog action
  examples/mirai_gallery/assets/json/dialog_example.json
  examples/mirai_gallery/assets/json/home_screen.json
  packages/mirai/lib/src/action_parsers/action_parsers.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action.g.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action.g.dart
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/navigation/mirai_navigator.dart
  packages/mirai/lib/src/utils/action_type.dart
Labels: feature, breaking-change

#199 feat: Return FutureBuilder in Mirai.fromAsset
  examples/mirai_gallery/lib/app/example/example_screen_parser.dart
  examples/mirai_gallery/lib/app/home/home_screen.dart
  packages/mirai/lib/mirai.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action.g.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action_parser.dart
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/navigation/mirai_navigator.dart
  packages/mirai/lib/src/navigation/navigation.dart
Labels: feature, breaking-change

#205 feat: Added `fontFamily` and `fontFamilyFallback` support in `MiraiTheme` and `MiraiTextStyle`
  examples/mirai_gallery/assets/fonts/Handjet/Handjet-Bold.ttf
  examples/mirai_gallery/assets/fonts/Handjet/Handjet-Medium.ttf
  examples/mirai_gallery/assets/fonts/Handjet/Handjet-Regular.ttf
  examples/mirai_gallery/assets/json/example_light_theme.json
  examples/mirai_gallery/ios/Podfile
  examples/mirai_gallery/lib/main.dart
  examples/mirai_gallery/macos/Podfile
  examples/mirai_gallery/pubspec.lock
  examples/mirai_gallery/pubspec.yaml
  packages/mirai/lib/src/parsers/mirai_text_style/mirai_text_style.dart
  packages/mirai/lib/src/parsers/mirai_text_style/mirai_text_style.freezed.dart
  packages/mirai/lib/src/parsers/mirai_text_style/mirai_text_style.g.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.freezed.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.g.dart
  packages/mirai_webview/.flutter-plugins
  packages/mirai_webview/.flutter-plugins-dependencies
Labels: feature

#208 chore: Update Mirai to v0.5.1
  examples/mirai_gallery/pubspec.lock
  examples/mirai_gallery/pubspec.yaml
  packages/mirai/CHANGELOG.md
  packages/mirai/pubspec.yaml
  packages/mirai_webview/CHANGELOG.md
  packages/mirai_webview/example/README.md
  packages/mirai_webview/pubspec.yaml
Labels: chore

#210 chore: update readme
  examples/mirai_gallery/pubspec.lock
  packages/mirai_framework/CHANGELOG.md
  packages/mirai_framework/README.md
  packages/mirai_framework/pubspec.yaml
Labels: chore
