Repository Securrency-OSS/mirai, pull requests merged in 2023-03, with the labels that each got.

#78 Added box-fit support for the Mirai image.
  examples/mirai_gallery/assets/images/example_image_1.jpeg
  examples/mirai_gallery/assets/images/example_image_2.jpeg
  examples/mirai_gallery/assets/json/image_example.json
  examples/mirai_gallery/pubspec.yaml
  packages/mirai/lib/src/parsers/mirai_image/mirai_image.dart
  packages/mirai/lib/src/parsers/mirai_image/mirai_image.freezed.dart
  packages/mirai/lib/src/parsers/mirai_image/mirai_image.g.dart
  packages/mirai/lib/src/parsers/mirai_image/mirai_image_parser.dart
Labels: feature

#76 `ThemeData` integration and enabling dark/light mode in example app
  examples/mirai_gallery/assets/json/app_bar_example.json
  examples/mirai_gallery/assets/json/bottom_nav_bar_example.json
  examples/mirai_gallery/assets/json/card_example.json
  examples/mirai_gallery/assets/json/column_example.json
  examples/mirai_gallery/assets/json/container_example.json
  examples/mirai_gallery/assets/json/default_tab_controller_example.json
  examples/mirai_gallery/assets/json/dialog_example.json
  examples/mirai_gallery/assets/json/elevated_button_example.json
  examples/mirai_gallery/assets/json/example_dark_theme.json
  examples/mirai_gallery/assets/json/example_light_theme.json
  examples/mirai_gallery/assets/json/floating_action_button_example.json
  examples/mirai_gallery/assets/json/home_screen.json
  examples/mirai_gallery/assets/json/icon_button_example.json
  examples/mirai_gallery/assets/json/icon_example.json
  examples/mirai_gallery/assets/json/image_example.json
  examples/mirai_gallery/assets/json/list_tile_example.json
  examples/mirai_gallery/assets/json/list_view_example.json
  examples/mirai_gallery/assets/json/outlined_button_example.json
  examples/mirai_gallery/assets/json/padding_example.json
  examples/mirai_gallery/assets/json/row_example.json
  examples/mirai_gallery/assets/json/scaffold_example.json
  examples/mirai_gallery/assets/json/scroll_view_example.json
  examples/mirai_gallery/assets/json/sized_box_example.json
  examples/mirai_gallery/assets/json/tab_bar_example.json
  examples/mirai_gallery/assets/json/tab_bar_view_example.json
  examples/mirai_gallery/assets/json/text_button_example.json
  examples/mirai_gallery/assets/json/text_example.json
  examples/mirai_gallery/assets/json/text_field_example.json
  examples/mirai_gallery/lib/app/example/example_screen_parser.dart
  examples/mirai_gallery/lib/app_theme/app_theme_cubit.dart
  examples/mirai_gallery/lib/app_theme/app_theme_state.dart
  examples/mirai_gallery/lib/main.dart
  examples/mirai_gallery/pubspec.lock
  examples/mirai_gallery/pubspec.yaml
  packages/mirai/lib/src/framework/mirai_app.dart
  packages/mirai/lib/src/parsers/mirai_color_scheme/mirai_color_scheme.dart
  packages/mirai/lib/src/parsers/mirai_color_scheme/mirai_color_scheme.freezed.dart
  packages/mirai/lib/src/parsers/mirai_color_scheme/mirai_color_scheme.g.dart
  packages/mirai/lib/src/parsers/mirai_material_color/mirai_material_color.dart
  packages/mirai/lib/src/parsers/mirai_material_color/mirai_material_color.freezed.dart
  packages/mirai/lib/src/parsers/mirai_material_color/mirai_material_color.g.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.freezed.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.g.dart
  packages/mirai/lib/src/parsers/parsers.dart
Labels: feature

#81 fix: Refactor app bar to PreferredSizeWidget
  packages/mirai/lib/src/action/mirai_action_parser.dart
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/parsers/mirai_alert_dialog/mirai_alert_dialog_parser.dart
  packages/mirai/lib/src/parsers/mirai_app_bar/mirai_app_bar_parser.dart
  packages/mirai/lib/src/parsers/mirai_column/mirai_column_parser.dart
  packages/mirai/lib/src/parsers/mirai_default_tab_controller/mirai_default_tab_controller_parser.dart
  packages/mirai/lib/src/parsers/mirai_floating_action_button/mirai_floating_action_button_parser.dart
  packages/mirai/lib/src/parsers/mirai_icon_button/mirai_icon_button_parser.dart
  packages/mirai/lib/src/parsers/mirai_list_view/mirai_list_view_parser.dart
  packages/mirai/lib/src/parsers/mirai_navigation_bar_item/mirai_bottom_navigation_bar_item.dart
  packages/mirai/lib/src/parsers/mirai_row/mirai_row_parser.dart
  packages/mirai/lib/src/parsers/mirai_scaffold/mirai_scaffold_parser.dart
  packages/mirai/lib/src/parsers/mirai_tab_bar/mirai_tab_bar_parser.dart
  packages/mirai/lib/src/parsers/mirai_tab_bar_view/mirai_tab_bar_view_parser.dart
  packages/mirai/lib/src/parsers/mirai_text_button/mirai_text_button_parser.dart
Labels: bug

#91 feat: Add support for `iconTheme` in `MiraiTheme`
  examples/mirai_gallery/assets/json/example_light_theme.json
  packages/mirai/lib/src/parsers/mirai_icon_theme_data/mirai_icon_theme_data.dart
  packages/mirai/lib/src/parsers/mirai_icon_theme_data/mirai_icon_theme_data.freezed.dart
  packages/mirai/lib/src/parsers/mirai_icon_theme_data/mirai_icon_theme_data.g.dart
  packages/mirai/lib/src/parsers/mirai_offset/mirai_offset.dart
  packages/mirai/lib/src/parsers/mirai_offset/mirai_offset.freezed.dart
  packages/mirai/lib/src/parsers/mirai_offset/mirai_offset.g.dart
  packages/mirai/lib/src/parsers/mirai_shadow/mirai_shadow.dart
  packages/mirai/lib/src/parsers/mirai_shadow/mirai_shadow.freezed.dart
  packages/mirai/lib/src/parsers/mirai_shadow/mirai_shadow.g.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.freezed.dart
  packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.g.dart
Labels: feature

#95 Add Mirai Tab parser
  examples/mirai_gallery/assets/json/home_screen.json
  examples/mirai_gallery/assets/json/tab_bar_example.json
  examples/mirai_gallery/assets/json/tab_bar_view_example.json
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/parsers/mirai_app_bar/mirai_app_bar.dart
  packages/mirai/lib/src/parsers/mirai_app_bar/mirai_app_bar.freezed.dart
  packages/mirai/lib/src/parsers/mirai_app_bar/mirai_app_bar.g.dart
  packages/mirai/lib/src/parsers/mirai_app_bar/mirai_app_bar_parser.dart
  packages/mirai/lib/src/parsers/mirai_tab/mirai_tab.dart
  packages/mirai/lib/src/parsers/mirai_tab/mirai_tab.freezed.dart
  packages/mirai/lib/src/parsers/mirai_tab/mirai_tab.g.dart
  packages/mirai/lib/src/parsers/mirai_tab/mirai_tab_parser.dart
  packages/mirai/lib/src/utils/widget_type.dart
Labels: feature

#97 Mirai v0.1 release
  README.md
  packages/mirai/CHANGELOG.md
  packages/mirai/README.md
  packages/mirai/pubspec.yaml
Labels: chore
