Repository Securrency-OSS/mirai, pull requests merged in 2024-02, with the labels that each got.

#252 fix: Rename scrollView to SingleChildScrollView
  examples/mirai_gallery/macos/Podfile.lock
  examples/mirai_gallery/macos/Runner.xcodeproj/project.pbxproj
  examples/mirai_gallery/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  examples/mirai_gallery/pubspec.lock
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action.g.dart
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/parsers/mirai_align/mirai_align.dart
  packages/mirai/lib/src/parsers/mirai_center/mirai_center.dart
  packages/mirai/lib/src/parsers/mirai_check_box_widget/mirai_check_box_widget.dart
  packages/mirai/lib/src/parsers/mirai_form/mirai_form.dart
  packages/mirai/lib/src/parsers/mirai_form_field/mirai_form_field.dart
  packages/mirai/lib/src/parsers/mirai_fractionally_sized_box/mirai_fractionally_sized_box.dart
  packages/mirai/lib/src/parsers/mirai_refresh_indicator/mirai_refresh_indicator_parser.dart
  packages/mirai/lib/src/parsers/mirai_single_child_scroll_view/mirai_single_child_scroll_view.dart
  packages/mirai/lib/src/parsers/mirai_single_child_scroll_view/mirai_single_child_scroll_view.freezed.dart
  packages/mirai/lib/src/parsers/mirai_single_child_scroll_view/mirai_single_child_scroll_view.g.dart
  packages/mirai/lib/src/parsers/mirai_single_child_scroll_view/mirai_single_child_scroll_view_parser.dart
  packages/mirai/lib/src/parsers/mirai_switch/mirai_switch.dart
  packages/mirai/lib/src/parsers/mirai_switch/mirai_switch_parser.dart
  packages/mirai/lib/src/parsers/mirai_switch/widget/mirai_switch_widget.dart
  packages/mirai/lib/src/parsers/mirai_tab/mirai_tab.dart
  packages/mirai/lib/src/parsers/parsers.dart
  packages/mirai/lib/src/utils/widget_type.dart
Labels: enhancement

#262 feat: Mirai Grid View
  examples/mirai_gallery/assets/json/grid_view_example.json
  examples/mirai_gallery/assets/json/home_screen.json
  examples/mirai_gallery/ios/Podfile.lock
  examples/mirai_gallery/ios/Runner.xcodeproj/project.pbxproj
  examples/mirai_gallery/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/parsers/mirai_grid_view/mirai_grid_view.dart
  packages/mirai/lib/src/parsers/mirai_grid_view/mirai_grid_view.freezed.dart
  packages/mirai/lib/src/parsers/mirai_grid_view/mirai_grid_view.g.dart
  packages/mirai/lib/src/parsers/mirai_grid_view/mirai_grid_view_parser.dart
  packages/mirai/lib/src/parsers/parsers.dart
  packages/mirai/lib/src/utils/widget_type.dart
Labels: feature

#267 feat: Add Mirai Network Request & Network Result
  packages/mirai/lib/mirai.dart
  packages/mirai/lib/src/action_parsers/action_parsers.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action.g.dart
  packages/mirai/lib/src/action_parsers/mirai_dialog_action/mirai_dialog_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action.g.dart
  packages/mirai/lib/src/action_parsers/mirai_modal_bottom_sheet_action/mirai_modal_bottom_sheet_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action.g.dart
  packages/mirai/lib/src/action_parsers/mirai_navigate_action/mirai_navigate_action_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request.dart
  packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request.g.dart
  packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_request_action/mirai_request_action_parser.dart
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/network/mirai_network.dart
  packages/mirai/lib/src/network/mirai_request.dart
  packages/mirai/lib/src/network/mirai_request.freezed.dart
  packages/mirai/lib/src/network/mirai_request.g.dart
  packages/mirai/lib/src/network/network.dart
  packages/mirai/lib/src/parsers/mirai_network_widget/mirai_network_widget.dart
  packages/mirai/lib/src/parsers/mirai_network_widget/mirai_network_widget.freezed.dart
  packages/mirai/lib/src/parsers/mirai_network_widget/mirai_network_widget.g.dart
  packages/mirai/lib/src/parsers/mirai_network_widget/mirai_network_widget_parser.dart
  packages/mirai/lib/src/services/mirai_network_service.dart
  packages/mirai/lib/src/utils/action_type.dart
Labels: feature, breaking-change

#266 feat: Revamp Mirai Form to add form validation, getting form values and submitting Form
  examples/mirai_gallery/assets/json/app_bar_example.json
  examples/mirai_gallery/assets/json/form_example.json
  examples/mirai_gallery/lib/main.dart
  packages/mirai/lib/src/action_parsers/action_parsers.dart
  packages/mirai/lib/src/action_parsers/mirai_form_validate/mirai_form_validate.dart
  packages/mirai/lib/src/action_parsers/mirai_form_validate/mirai_form_validate.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_form_validate/mirai_form_validate.g.dart
  packages/mirai/lib/src/action_parsers/mirai_form_validate/mirai_form_validate_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_get_form_value/mirai_get_form_value.dart
  packages/mirai/lib/src/action_parsers/mirai_get_form_value/mirai_get_form_value.freezed.dart
  packages/mirai/lib/src/action_parsers/mirai_get_form_value/mirai_get_form_value.g.dart
  packages/mirai/lib/src/action_parsers/mirai_get_form_value/mirai_get_form_value_parser.dart
  packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request_parser.dart
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/parsers/mirai_check_box_widget/mirai_check_box_widget_parser.dart
  packages/mirai/lib/src/parsers/mirai_form/cubit/mirai_form_cubit.dart
  packages/mirai/lib/src/parsers/mirai_form/cubit/mirai_form_state.dart
  packages/mirai/lib/src/parsers/mirai_form/mirai_form_parser.dart
  packages/mirai/lib/src/parsers/mirai_form/mirai_form_scope.dart
  packages/mirai/lib/src/parsers/mirai_form_field/mirai_form_field.dart
  packages/mirai/lib/src/parsers/mirai_form_field/mirai_form_field.freezed.dart
  packages/mirai/lib/src/parsers/mirai_form_field/mirai_form_field.g.dart
  packages/mirai/lib/src/parsers/mirai_form_field/mirai_form_field_parser.dart
  packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field_parser.dart
  packages/mirai/lib/src/parsers/parsers.dart
  packages/mirai/lib/src/utils/action_type.dart
  packages/mirai/pubspec.yaml
Labels: feature, breaking-change

#275 feat: Add defaultBottomNavigationController & bottomNavigationView
  examples/mirai_gallery/assets/json/bottom_nav_bar_example.json
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_bar/mirai_bottom_navigation_bar.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_bar/mirai_bottom_navigation_bar.freezed.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_bar/mirai_bottom_navigation_bar.g.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_bar/mirai_bottom_navigation_bar_parser.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_view/mirai_bottom_navigation_view.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_view/mirai_bottom_navigation_view.freezed.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_view/mirai_bottom_navigation_view.g.dart
  packages/mirai/lib/src/parsers/mirai_bottom_navigation_view/mirai_bottom_navigation_view_parser.dart
  packages/mirai/lib/src/parsers/mirai_default_bottom_navigation_controller/mirai_default_bottom_navigation_controller.dart
  packages/mirai/lib/src/parsers/mirai_default_bottom_navigation_controller/mirai_default_bottom_navigation_controller.freezed.dart
  packages/mirai/lib/src/parsers/mirai_default_bottom_navigation_controller/mirai_default_bottom_navigation_controller.g.dart
  packages/mirai/lib/src/parsers/mirai_default_bottom_navigation_controller/mirai_default_bottom_navigation_controller_parser.dart
  packages/mirai/lib/src/parsers/mirai_navigation_bar_item/mirai_bottom_navigation_bar_item.dart
  packages/mirai/lib/src/parsers/parsers.dart
  packages/mirai/lib/src/utils/widget_type.dart
Labels: feature

#277 feat: Add support to the Wrap widget
  examples/mirai_gallery/assets/json/home_screen.json
  examples/mirai_gallery/assets/json/wrap_example.json
  packages/mirai/lib/src/framework/mirai.dart
  packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap.dart
  packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap.freezed.dart
  packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap.g.dart
  packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap_parser.dart
  packages/mirai/lib/src/parsers/parsers.dart
  packages/mirai/lib/src/utils/widget_type.dart
Labels: feature

#276 feat: Added a new way to redefine how we declare EdgeInsets
  packages/mirai/lib/src/parsers/mirai_alert_dialog/mirai_alert_dialog.g.dart
  packages/mirai/lib/src/parsers/mirai_bottom_app_bar_theme/mirai_bottom_app_bar_theme.g.dart
  packages/mirai/lib/src/parsers/mirai_button_style/mirai_button_style.g.dart
  packages/mirai/lib/src/parsers/mirai_card/mirai_card.g.dart
  packages/mirai/lib/src/parsers/mirai_card_theme_data/mirai_card_theme_data.g.dart
  packages/mirai/lib/src/parsers/mirai_chip/mirai_chip.g.dart
  packages/mirai/lib/src/parsers/mirai_container/mirai_container.g.dart
  packages/mirai/lib/src/parsers/mirai_dialog_theme/mirai_dialog_theme.g.dart
  packages/mirai/lib/src/parsers/mirai_edge_insets/mirai_edge_insets.dart
  packages/mirai/lib/src/parsers/mirai_floating_action_button_theme_data/mirai_floating_action_button_theme_data.g.dart
  packages/mirai/lib/src/parsers/mirai_grid_view/mirai_grid_view.g.dart
  packages/mirai/lib/src/parsers/mirai_icon_button/mirai_icon_button.g.dart
  packages/mirai/lib/src/parsers/mirai_input_decoration/mirai_input_decoration.g.dart
  packages/mirai/lib/src/parsers/mirai_input_decoration_theme/mirai_input_decoration_theme.g.dart
  packages/mirai/lib/src/parsers/mirai_list_tile/mirai_list_tile.g.dart
  packages/mirai/lib/src/parsers/mirai_list_tile_theme_data/mirai_list_tile_theme_data.g.dart
  packages/mirai/lib/src/parsers/mirai_list_view/mirai_list_view.g.dart
  packages/mirai/lib/src/parsers/mirai_padding/mirai_padding.g.dart
  packages/mirai/lib/src/parsers/mirai_safe_area/mirai_safe_area.g.dart
  packages/mirai/lib/src/parsers/mirai_single_child_scroll_view/mirai_single_child_scroll_view.g.dart
  packages/mirai/lib/src/parsers/mirai_tab/mirai_tab.g.dart
  packages/mirai/lib/src/parsers/mirai_tab_bar/mirai_tab_bar.g.dart
  packages/mirai/lib/src/parsers/mirai_tab_bar_theme_data/mirai_tab_bar_theme_data.g.dart
  packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field.g.dart
Labels: feature
